<option value='' selected=''>SELECT ONE --&gt;</option>
<option value='Switzerland (SUI)'>Switzerland (SUI)</option>
<option value='Great Britain (GBR)'>Great Britain (GBR)</option>
<option value='France (FRA)'>France (FRA)</option>
<option value='Italy (ITA)'>Italy (ITA)</option>
<option value='Hungary (HUN)'>Hungary (HUN)</option>
<option value='Ireland (IRL)'>Ireland (IRL)</option>
<option value='Belgium (BEL)'>Belgium (BEL)</option>
<option value='Netherlands (NED)'>Netherlands (NED)</option>
<option value='Malta (MLT)'>Malta (MLT)</option>
<option value='Spain (ESP)'>Spain (ESP)</option>
<option value='Czech Republic (CZE)'>Czech Republic (CZE)</option>
<option value='Denmark (DEN)'>Denmark (DEN)</option>
<option value='Portugal (POR)'>Portugal (POR)</option>
<option value='Germany (GER)'>Germany (GER)</option>
<option value='Latvia (LAT)'>Latvia (LAT)</option>
<option value='Croatia (CRO)'>Croatia (CRO)</option>

<option value=''>- - - - - - -</option>

<option value='Sweden (SWE)'>Sweden (SWE)</option>
<option value='Afghanistan (AFG)'>Afghanistan (AFG)</option>
<option value='Albania (ALB)'>Albania (ALB)</option>
<option value='Algeria (ALG)'>Algeria (ALG)</option>
<option value='Andorra (AND)'>Andorra (AND)</option>
<option value='Angola (ANG)'>Angola (ANG)</option>
<option value='Antigua and Barbuda (ANT)'>Antigua and Barbuda (ANT)</option>
<option value='Argentina (ARG)'>Argentina (ARG)</option>
<option value='Armenia (ARM)'>Armenia (ARM)</option>
<option value='Aruba (ARU)'>Aruba (ARU)</option>
<option value='American Samoa (ASA)'>American Samoa (ASA)</option>
<option value='Australia (AUS)'>Australia (AUS)</option>
<option value='Austria (AUT)'>Austria (AUT)</option>
<option value='Azerbaijan (AZE)'>Azerbaijan (AZE)</option>
<option value='Bahamas (BAH)'>Bahamas (BAH)</option>
<option value='Bangladesh (BAN)'>Bangladesh (BAN)</option>
<option value='Barbados (BAR)'>Barbados (BAR)</option>
<option value='Burundi (BDI)'>Burundi (BDI)</option>
<option value='Benin (BEN)'>Benin (BEN)</option>
<option value='Bermuda (BER)'>Bermuda (BER)</option>
<option value='Bhutan (BHU)'>Bhutan (BHU)</option>
<option value='Bosnia and Herzegovina (BIH)'>Bosnia and Herzegovina (BIH)</option>
<option value='Belize (BIZ)'>Belize (BIZ)</option>
<!--option value='Belarus (BLR)'>Belarus (BLR)</option-->
<option value='Bolivia (BOL)'>Bolivia (BOL)</option>
<option value='Botswana (BOT)'>Botswana (BOT)</option>
<option value='Brazil (BRA)'>Brazil (BRA)</option>
<option value='Bahrain (BRN)'>Bahrain (BRN)</option>
<option value='Brunei (BRU)'>Brunei (BRU)</option>
<option value='Bulgaria (BUL)'>Bulgaria (BUL)</option>
<option value='Burkina Faso (BUR)'>Burkina Faso (BUR)</option>
<option value='Central African Republic (CAF)'>Central African Republic (CAF)</option>
<option value='Cambodia (CAM)'>Cambodia (CAM)</option>
<option value='Canada (CAN)'>Canada (CAN)</option>
<option value='Cayman Islands (CAY)'>Cayman Islands (CAY)</option>
<option value='Republic of the Congo (CGO)'>Republic of the Congo (CGO)</option>
<option value='Chad (CHA)'>Chad (CHA)</option>
<option value='Chile (CHI)'>Chile (CHI)</option>
<option value='China (CHN)'>China (CHN)</option>
<option value='Ivory Coast (CIV)'>Ivory Coast (CIV)</option>
<option value='Cameroon (CMR)'>Cameroon (CMR)</option>
<option value='Democratic Republic of Congo (COD)'>Democ. Rep. of Congo (COD)</option>
<option value='Cook Islands (COK)'>Cook Islands (COK)</option>
<option value='Colombia (COL)'>Colombia (COL)</option>
<option value='Comoros (COM)'>Comoros (COM)</option>
<option value='Cape Verde (CPV)'>Cape Verde (CPV)</option>
<option value='Costa Rica (CRC)'>Costa Rica (CRC)</option>
<option value='Cuba (CUB)'>Cuba (CUB)</option>
<option value='Cyprus (CYP)'>Cyprus (CYP)</option>
<option value='Djibouti (DJI)'>Djibouti (DJI)</option>
<option value='Dominica (DMA)'>Dominica (DMA)</option>
<option value='Dominican Republic (DOM)'>Dominican Republic (DOM)</option>
<option value='Ecuador (ECU)'>Ecuador (ECU)</option>
<option value='Egypt (EGY)'>Egypt (EGY)</option>
<option value='Eritrea (ERI)'>Eritrea (ERI)</option>
<option value='El Salvador (ESA)'>El Salvador (ESA)</option>
<option value='Estonia (EST)'>Estonia (EST)</option>
<option value='Ethiopia (ETH)'>Ethiopia (ETH)</option>
<option value='Fiji (FIJ)'>Fiji (FIJ)</option>
<option value='Finland (FIN)'>Finland (FIN)</option>
<option value='Federated States of Micronesia (FSM)'>Fed. States of Micronesia (FSM)</option>
<option value='Gabon (GAB)'>Gabon (GAB)</option>
<option value='The Gambia (GAM)'>The Gambia (GAM)</option>
<option value='Guinea-Bissau (GBS)'>Guinea-Bissau (GBS)</option>
<option value='Georgia (GEO)'>Georgia (GEO)</option>
<option value='Equatorial Guinea (GEQ)'>Equatorial Guinea (GEQ)</option>
<option value='Ghana (GHA)'>Ghana (GHA)</option>
<option value='Greece (GRE)'>Greece (GRE)</option>
<option value='Grenada (GRN)'>Grenada (GRN)</option>
<option value='Guatemala (GUA)'>Guatemala (GUA)</option>
<option value='Guinea (GUI)'>Guinea (GUI)</option>
<option value='Guam (GUM)'>Guam (GUM)</option>
<option value='Guyana (GUY)'>Guyana (GUY)</option>
<option value='Haiti (HAI)'>Haiti (HAI)</option>
<option value='Hong Kong, China (HKG)'>Hong Kong, China (HKG)</option>
<option value='Honduras (HON)'>Honduras (HON)</option>
<option value='Indonesia (INA)'>Indonesia (INA)</option>
<option value='India (IND)'>India (IND)</option>
<option value='Iran (IRI)'>Iran (IRI)</option>
<option value='Iraq (IRQ)'>Iraq (IRQ)</option>
<option value='Iceland (ISL)'>Iceland (ISL)</option>
<option value='Israel (ISR)'>Israel (ISR)</option>
<option value='Virgin Islands (ISV)'>Virgin Islands (ISV)</option>
<option value='British Virgin Islands (IVB)'>British Virgin Islands (IVB)</option>
<option value='Jamaica (JAM)'>Jamaica (JAM)</option>
<option value='Jordan (JOR)'>Jordan (JOR)</option>
<option value='Japan (JPN)'>Japan (JPN)</option>
<option value='Kazakhstan (KAZ)'>Kazakhstan (KAZ)</option>
<option value='Kenya (KEN)'>Kenya (KEN)</option>
<option value='Kyrgyzstan (KGZ)'>Kyrgyzstan (KGZ)</option>
<option value='Kiribati (KIR)'>Kiribati (KIR)</option>
<option value='South Korea (KOR)'>South Korea (KOR)</option>
<option value='Kosovo (KOS)'>Kosovo (KOS)</option>
<option value='Saudi Arabia (KSA)'>Saudi Arabia (KSA)</option>
<option value='Kuwait (KUW)'>Kuwait (KUW)</option>
<option value='Laos (LAO)'>Laos (LAO)</option>
<option value='Libya (LBA)'>Libya (LBA)</option>
<option value='Lebanon (LBN)'>Lebanon (LBN)</option>
<option value='Liberia (LBR)'>Liberia (LBR)</option>
<option value='Saint Lucia (LCA)'>Saint Lucia (LCA)</option>
<option value='Lesotho (LES)'>Lesotho (LES)</option>
<option value='Liechtenstein (LIE)'>Liechtenstein (LIE)</option>
<option value='Lithuania (LTU)'>Lithuania (LTU)</option>
<option value='Luxembourg (LUX)'>Luxembourg (LUX)</option>
<option value='Madagascar (MAD)'>Madagascar (MAD)</option>
<option value='Morocco (MAR)'>Morocco (MAR)</option>
<option value='Malaysia (MAS)'>Malaysia (MAS)</option>
<option value='Malawi (MAW)'>Malawi (MAW)</option>
<option value='Moldova (MDA)'>Moldova (MDA)</option>
<option value='Maldives (MDV)'>Maldives (MDV)</option>
<option value='Mexico (MEX)'>Mexico (MEX)</option>
<option value='Mongolia (MGL)'>Mongolia (MGL)</option>
<option value='Marshall Islands (MHL)'>Marshall Islands (MHL)</option>
<option value='Macedonia (MKD)'>Macedonia (MKD)</option>
<option value='Mali (MLI)'>Mali (MLI)</option>
<option value='Montenegro (MNE)'>Montenegro (MNE)</option>
<option value='Monaco (MON)'>Monaco (MON)</option>
<option value='Mozambique (MOZ)'>Mozambique (MOZ)</option>
<option value='Mauritius (MRI)'>Mauritius (MRI)</option>
<option value='Mauritania (MTN)'>Mauritania (MTN)</option>
<option value='Myanmar (MYA)'>Myanmar (MYA)</option>
<option value='Namibia (NAM)'>Namibia (NAM)</option>
<option value='Nicaragua (NCA)'>Nicaragua (NCA)</option>
<option value='Nepal (NEP)'>Nepal (NEP)</option>
<option value='Nigeria (NGR)'>Nigeria (NGR)</option>
<option value='Niger (NIG)'>Niger (NIG)</option>
<option value='Norway (NOR)'>Norway (NOR)</option>
<option value='Nauru (NRU)'>Nauru (NRU)</option>
<option value='New Zealand (NZL)'>New Zealand (NZL)</option>
<option value='Oman (OMA)'>Oman (OMA)</option>
<option value='Pakistan (PAK)'>Pakistan (PAK)</option>
<option value='Panama (PAN)'>Panama (PAN)</option>
<option value='Paraguay (PAR)'>Paraguay (PAR)</option>
<option value='Peru (PER)'>Peru (PER)</option>
<option value='Philippines (PHI)'>Philippines (PHI)</option>
<option value='Palestine (PLE)'>Palestine (PLE)</option>
<option value='Palau (PLW)'>Palau (PLW)</option>
<option value='Papua New Guinea (PNG)'>Papua New Guinea (PNG)</option>
<option value='Poland (POL)'>Poland (POL)</option>
<option value='North Korea (PRK)'>North Korea (PRK)</option>
<option value='Puerto Rico (PUR)'>Puerto Rico (PUR)</option>
<option value='Qatar (QAT)'>Qatar (QAT)</option>
<option value='Romania (ROU)'>Romania (ROU)</option>
<option value='South Africa (RSA)'>South Africa (RSA)</option>
<!--option value='Russia (RUS)'>Russia (RUS)</option-->
<option value='Rwanda (RWA)'>Rwanda (RWA)</option>
<option value='Samoa (SAM)'>Samoa (SAM)</option>
<option value='Senegal (SEN)'>Senegal (SEN)</option>
<option value='Seychelles (SEY)'>Seychelles (SEY)</option>
<option value='Singapore (SGP)'>Singapore (SGP)</option>
<option value='Saint Kitts and Nevis (SKN)'>Saint Kitts and Nevis (SKN)</option>
<option value='Sierra Leone (SLE)'>Sierra Leone (SLE)</option>
<option value='Slovenia (SLO)'>Slovenia (SLO)</option>
<option value='San Marino (SMR)'>San Marino (SMR)</option>
<option value='Solomon Islands (SOL)'>Solomon Islands (SOL)</option>
<option value='Somalia (SOM)'>Somalia (SOM)</option>
<option value='Serbia (SRB)'>Serbia (SRB)</option>
<option value='Sri Lanka (SRI)'>Sri Lanka (SRI)</option>
<option value='South Sudan (SSD)'>South Sudan (SSD)</option>
<option value='São Tomé and Príncipe (STP)'>São Tomé and Príncipe (STP)</option>
<option value='Sudan (SUD)'>Sudan (SUD)</option>
<option value='Suriname (SUR)'>Suriname (SUR)</option>
<option value='Slovakia (SVK)'>Slovakia (SVK)</option>
<option value='Swaziland (SWZ)'>Swaziland (SWZ)</option>
<option value='Syria (SYR)'>Syria (SYR)</option>
<option value='Tanzania (TAN)'>Tanzania (TAN)</option>
<option value='Tonga (TGA)'>Tonga (TGA)</option>

<option value='Thailand (THA)'>Thailand (THA)</option>
<option value='Tajikistan (TJK)'>Tajikistan (TJK)</option>
<option value='Turkmenistan (TKM)'>Turkmenistan (TKM)</option>
<option value='East Timor (TLS)'>East Timor (TLS)</option>
<option value='Togo (TOG)'>Togo (TOG)</option>
<option value='Chinese Taipei (TPE)'>Chinese Taipei (TPE)</option>
<option value='Trinidad and Tobago (TTO)'>Trinidad and Tobago (TTO)</option>
<option value='Tunisia (TUN)'>Tunisia (TUN)</option>
<option value='Turkey (TUR)'>Turkey (TUR)</option>
<option value='Tuvalu (TUV)'>Tuvalu (TUV)</option>
<option value='United Arab Emirates (UAE)'>United Arab Emirates (UAE)</option>
<option value='Uganda (UGA)'>Uganda (UGA)</option>
<option value='Ukraine (UKR)'>Ukraine (UKR)</option>
<option value='Uruguay (URU)'>Uruguay (URU)</option>
<option value='United States (USA)'>United States (USA)</option>
<option value='Uzbekistan (UZB)'>Uzbekistan (UZB)</option>
<option value='Vanuatu (VAN)'>Vanuatu (VAN)</option>
<option value='Venezuela (VEN)'>Venezuela (VEN)</option>
<option value='Vietnam (VIE)'>Vietnam (VIE)</option>
<option value='Saint Vincent and the Grenadines (VIN)'>S.Vincent and Grenadines (VIN)</option>
<option value='Yemen (YEM)'>Yemen (YEM)</option>
<option value='Zambia (ZAM)'>Zambia (ZAM)</option>
<option value='Zimbabwe (ZIM)'>Zimbabwe (ZIM)</option>
