INSERT INTO Eap (CountryCode, FullName) VALUES ('Amsterdam', 'Amsterdam(NED)');
INSERT INTO Eap (CountryCode, FullName) VALUES ('Annecy', 'Annecy(FRA)');
INSERT INTO Eap (CountryCode, FullName) VALUES ('Budapest', 'Budapest(HUN)');
INSERT INTO Eap (CountryCode, FullName) VALUES ('Catania', 'Catania(ITA)');
INSERT INTO Eap (CountryCode, FullName) VALUES ('Celle Ligure', 'Celle Ligure(ITA)');
INSERT INTO Eap (CountryCode, FullName) VALUES ('Donnas', 'Donnas(ITA)');
INSERT INTO Eap (CountryCode, FullName) VALUES ('Geneve', 'Geneve(SUI)');
INSERT INTO Eap (CountryCode, FullName) VALUES ('Kuldiga', 'Kuldiga(LAT)');
INSERT INTO Eap (CountryCode, FullName) VALUES ('Loughborough', 'Loughborough(UK)');
INSERT INTO Eap (CountryCode, FullName) VALUES ('Malta', 'Malta(MLT)');
INSERT INTO Eap (CountryCode, FullName) VALUES ('Nivelles', 'Nivelles(BEL)');
INSERT INTO Eap (CountryCode, FullName) VALUES ('Palafrugell', 'Palafrugell(ESP)');
INSERT INTO Eap (CountryCode, FullName) VALUES ('San Vito', 'San Vito(ITA)');
INSERT INTO Eap (CountryCode, FullName) VALUES ('Villa Manin', 'Villa Manin(ITA)');

INSERT INTO Countries (CountryCode, FullName) VALUES ('SUI', 'Switzerland');
INSERT INTO Countries (CountryCode, FullName) VALUES ('GBR', 'Great Britain');
INSERT INTO Countries (CountryCode, FullName) VALUES ('FRA', 'France');
INSERT INTO Countries (CountryCode, FullName) VALUES ('ITA', 'Italy');
INSERT INTO Countries (CountryCode, FullName) VALUES ('HUN', 'Hungary');
INSERT INTO Countries (CountryCode, FullName) VALUES ('IRL', 'Ireland');
INSERT INTO Countries (CountryCode, FullName) VALUES ('BEL', 'Belgium');
INSERT INTO Countries (CountryCode, FullName) VALUES ('NED', 'Netherlands');
INSERT INTO Countries (CountryCode, FullName) VALUES ('MLT', 'Malta');
INSERT INTO Countries (CountryCode, FullName) VALUES ('ESP', 'Spain');
INSERT INTO Countries (CountryCode, FullName) VALUES ('CZE', 'Czech Republic');
INSERT INTO Countries (CountryCode, FullName) VALUES ('DEN', 'Denmark');
INSERT INTO Countries (CountryCode, FullName) VALUES ('POR', 'Portugal');
INSERT INTO Countries (CountryCode, FullName) VALUES ('GER', 'Germany');
INSERT INTO Countries (CountryCode, FullName) VALUES ('LAT', 'Latvia');
INSERT INTO Countries (CountryCode, FullName) VALUES ('CRO', 'Croatia');

INSERT INTO Countries (CountryCode, FullName) VALUES ('SWE', 'Sweden');
INSERT INTO Countries (CountryCode, FullName) VALUES ('AFG', 'Afghanistan');
INSERT INTO Countries (CountryCode, FullName) VALUES ('ALB', 'Albania');
INSERT INTO Countries (CountryCode, FullName) VALUES ('ALG', 'Algeria');
INSERT INTO Countries (CountryCode, FullName) VALUES ('AND', 'Andorra');
INSERT INTO Countries (CountryCode, FullName) VALUES ('ANG', 'Angola');
INSERT INTO Countries (CountryCode, FullName) VALUES ('ANT', 'Antigua and Barbuda');
INSERT INTO Countries (CountryCode, FullName) VALUES ('ARG', 'Argentina');
INSERT INTO Countries (CountryCode, FullName) VALUES ('ARM', 'Armenia');
INSERT INTO Countries (CountryCode, FullName) VALUES ('ARU', 'Aruba');
INSERT INTO Countries (CountryCode, FullName) VALUES ('ASA', 'American Samoa');
INSERT INTO Countries (CountryCode, FullName) VALUES ('AUS', 'Australia');
INSERT INTO Countries (CountryCode, FullName) VALUES ('AUT', 'Austria');
INSERT INTO Countries (CountryCode, FullName) VALUES ('AZE', 'Azerbaijan');
INSERT INTO Countries (CountryCode, FullName) VALUES ('BAH', 'Bahamas');
INSERT INTO Countries (CountryCode, FullName) VALUES ('BAN', 'Bangladesh');
INSERT INTO Countries (CountryCode, FullName) VALUES ('BAR', 'Barbados');
INSERT INTO Countries (CountryCode, FullName) VALUES ('BDI', 'Burundi');
INSERT INTO Countries (CountryCode, FullName) VALUES ('BEN', 'Benin');
INSERT INTO Countries (CountryCode, FullName) VALUES ('BER', 'Bermuda');
INSERT INTO Countries (CountryCode, FullName) VALUES ('BHU', 'Bhutan');
INSERT INTO Countries (CountryCode, FullName) VALUES ('BIH', 'Bosnia and Herzegovina');
INSERT INTO Countries (CountryCode, FullName) VALUES ('BIZ', 'Belize');
-- INSERT INTO Countries (CountryCode, FullName) VALUES ('BLR', 'Belarus');
INSERT INTO Countries (CountryCode, FullName) VALUES ('BOL', 'Bolivia');
INSERT INTO Countries (CountryCode, FullName) VALUES ('BOT', 'Botswana');
INSERT INTO Countries (CountryCode, FullName) VALUES ('BRA', 'Brazil');
INSERT INTO Countries (CountryCode, FullName) VALUES ('BRN', 'Bahrain');
INSERT INTO Countries (CountryCode, FullName) VALUES ('BRU', 'Brunei');
INSERT INTO Countries (CountryCode, FullName) VALUES ('BUL', 'Bulgaria');
INSERT INTO Countries (CountryCode, FullName) VALUES ('BUR', 'Burkina Faso');
INSERT INTO Countries (CountryCode, FullName) VALUES ('CAF', 'Central African Republic');
INSERT INTO Countries (CountryCode, FullName) VALUES ('CAM', 'Cambodia');
INSERT INTO Countries (CountryCode, FullName) VALUES ('CAN', 'Canada');
INSERT INTO Countries (CountryCode, FullName) VALUES ('CAY', 'Cayman Islands');
INSERT INTO Countries (CountryCode, FullName) VALUES ('CGO', 'Republic of the Congo');
INSERT INTO Countries (CountryCode, FullName) VALUES ('CHA', 'Chad');
INSERT INTO Countries (CountryCode, FullName) VALUES ('CHI', 'Chile');
INSERT INTO Countries (CountryCode, FullName) VALUES ('CHN', 'China');
INSERT INTO Countries (CountryCode, FullName) VALUES ('CIV', 'Ivory Coast');
INSERT INTO Countries (CountryCode, FullName) VALUES ('CMR', 'Cameroon');
INSERT INTO Countries (CountryCode, FullName) VALUES ('COD', 'Democratic Republic of Congo');
INSERT INTO Countries (CountryCode, FullName) VALUES ('COK', 'Cook Islands');
INSERT INTO Countries (CountryCode, FullName) VALUES ('COL', 'Colombia');
INSERT INTO Countries (CountryCode, FullName) VALUES ('COM', 'Comoros');
INSERT INTO Countries (CountryCode, FullName) VALUES ('CPV', 'Cape Verde');
INSERT INTO Countries (CountryCode, FullName) VALUES ('CRC', 'Costa Rica');
INSERT INTO Countries (CountryCode, FullName) VALUES ('CUB', 'Cuba');
INSERT INTO Countries (CountryCode, FullName) VALUES ('CYP', 'Cyprus');
INSERT INTO Countries (CountryCode, FullName) VALUES ('DJI', 'Djibouti');
INSERT INTO Countries (CountryCode, FullName) VALUES ('DMA', 'Dominica');
INSERT INTO Countries (CountryCode, FullName) VALUES ('DOM', 'Dominican Republic');
INSERT INTO Countries (CountryCode, FullName) VALUES ('ECU', 'Ecuador');
INSERT INTO Countries (CountryCode, FullName) VALUES ('EGY', 'Egypt');
INSERT INTO Countries (CountryCode, FullName) VALUES ('ERI', 'Eritrea');
INSERT INTO Countries (CountryCode, FullName) VALUES ('ESA', 'El Salvador');
INSERT INTO Countries (CountryCode, FullName) VALUES ('EST', 'Estonia');
INSERT INTO Countries (CountryCode, FullName) VALUES ('ETH', 'Ethiopia');
INSERT INTO Countries (CountryCode, FullName) VALUES ('FIJ', 'Fiji');
INSERT INTO Countries (CountryCode, FullName) VALUES ('FIN', 'Finland');
INSERT INTO Countries (CountryCode, FullName) VALUES ('FSM', 'Federated States of Micronesia');
INSERT INTO Countries (CountryCode, FullName) VALUES ('GAB', 'Gabon');
INSERT INTO Countries (CountryCode, FullName) VALUES ('GAM', 'The Gambia');
INSERT INTO Countries (CountryCode, FullName) VALUES ('GBS', 'Guinea-Bissau');
INSERT INTO Countries (CountryCode, FullName) VALUES ('GEO', 'Georgia');
INSERT INTO Countries (CountryCode, FullName) VALUES ('GEQ', 'Equatorial Guinea');
INSERT INTO Countries (CountryCode, FullName) VALUES ('GHA', 'Ghana');
INSERT INTO Countries (CountryCode, FullName) VALUES ('GRE', 'Greece');
INSERT INTO Countries (CountryCode, FullName) VALUES ('GRN', 'Grenada');
INSERT INTO Countries (CountryCode, FullName) VALUES ('GUA', 'Guatemala');
INSERT INTO Countries (CountryCode, FullName) VALUES ('GUI', 'Guinea');
INSERT INTO Countries (CountryCode, FullName) VALUES ('GUM', 'Guam');
INSERT INTO Countries (CountryCode, FullName) VALUES ('GUY', 'Guyana');
INSERT INTO Countries (CountryCode, FullName) VALUES ('HAI', 'Haiti');
INSERT INTO Countries (CountryCode, FullName) VALUES ('HKG', 'Hong Kong, China');
INSERT INTO Countries (CountryCode, FullName) VALUES ('HON', 'Honduras');
INSERT INTO Countries (CountryCode, FullName) VALUES ('INA', 'Indonesia');
INSERT INTO Countries (CountryCode, FullName) VALUES ('IND', 'India');
INSERT INTO Countries (CountryCode, FullName) VALUES ('IRI', 'Iran');
INSERT INTO Countries (CountryCode, FullName) VALUES ('IRQ', 'Iraq');
INSERT INTO Countries (CountryCode, FullName) VALUES ('ISL', 'Iceland');
INSERT INTO Countries (CountryCode, FullName) VALUES ('ISR', 'Israel');
INSERT INTO Countries (CountryCode, FullName) VALUES ('ISV', 'Virgin Islands');
INSERT INTO Countries (CountryCode, FullName) VALUES ('IVB', 'British Virgin Islands');
INSERT INTO Countries (CountryCode, FullName) VALUES ('JAM', 'Jamaica');
INSERT INTO Countries (CountryCode, FullName) VALUES ('JOR', 'Jordan');
INSERT INTO Countries (CountryCode, FullName) VALUES ('JPN', 'Japan');
INSERT INTO Countries (CountryCode, FullName) VALUES ('KAZ', 'Kazakhstan');
INSERT INTO Countries (CountryCode, FullName) VALUES ('KEN', 'Kenya');
INSERT INTO Countries (CountryCode, FullName) VALUES ('KGZ', 'Kyrgyzstan');
INSERT INTO Countries (CountryCode, FullName) VALUES ('KIR', 'Kiribati');
INSERT INTO Countries (CountryCode, FullName) VALUES ('KOR', 'South Korea');
INSERT INTO Countries (CountryCode, FullName) VALUES ('KOS', 'Kosovo');
INSERT INTO Countries (CountryCode, FullName) VALUES ('KSA', 'Saudi Arabia');
INSERT INTO Countries (CountryCode, FullName) VALUES ('KUW', 'Kuwait');
INSERT INTO Countries (CountryCode, FullName) VALUES ('LAO', 'Laos');
INSERT INTO Countries (CountryCode, FullName) VALUES ('LBA', 'Libya');
INSERT INTO Countries (CountryCode, FullName) VALUES ('LBN', 'Lebanon');
INSERT INTO Countries (CountryCode, FullName) VALUES ('LBR', 'Liberia');
INSERT INTO Countries (CountryCode, FullName) VALUES ('LCA', 'Saint Lucia');
INSERT INTO Countries (CountryCode, FullName) VALUES ('LES', 'Lesotho');
INSERT INTO Countries (CountryCode, FullName) VALUES ('LIE', 'Liechtenstein');
INSERT INTO Countries (CountryCode, FullName) VALUES ('LTU', 'Lithuania');
INSERT INTO Countries (CountryCode, FullName) VALUES ('LUX', 'Luxembourg');
INSERT INTO Countries (CountryCode, FullName) VALUES ('MAD', 'Madagascar');
INSERT INTO Countries (CountryCode, FullName) VALUES ('MAR', 'Morocco');
INSERT INTO Countries (CountryCode, FullName) VALUES ('MAS', 'Malaysia');
INSERT INTO Countries (CountryCode, FullName) VALUES ('MAW', 'Malawi');
INSERT INTO Countries (CountryCode, FullName) VALUES ('MDA', 'Moldova');
INSERT INTO Countries (CountryCode, FullName) VALUES ('MDV', 'Maldives');
INSERT INTO Countries (CountryCode, FullName) VALUES ('MEX', 'Mexico');
INSERT INTO Countries (CountryCode, FullName) VALUES ('MGL', 'Mongolia');
INSERT INTO Countries (CountryCode, FullName) VALUES ('MHL', 'Marshall Islands');
INSERT INTO Countries (CountryCode, FullName) VALUES ('MKD', 'Macedonia');
INSERT INTO Countries (CountryCode, FullName) VALUES ('MLI', 'Mali');
INSERT INTO Countries (CountryCode, FullName) VALUES ('MNE', 'Montenegro');
INSERT INTO Countries (CountryCode, FullName) VALUES ('MON', 'Monaco');
INSERT INTO Countries (CountryCode, FullName) VALUES ('MOZ', 'Mozambique');
INSERT INTO Countries (CountryCode, FullName) VALUES ('MRI', 'Mauritius');
INSERT INTO Countries (CountryCode, FullName) VALUES ('MTN', 'Mauritania');
INSERT INTO Countries (CountryCode, FullName) VALUES ('MYA', 'Myanmar');
INSERT INTO Countries (CountryCode, FullName) VALUES ('NAM', 'Namibia');
INSERT INTO Countries (CountryCode, FullName) VALUES ('NCA', 'Nicaragua');
INSERT INTO Countries (CountryCode, FullName) VALUES ('NEP', 'Nepal');
INSERT INTO Countries (CountryCode, FullName) VALUES ('NGR', 'Nigeria');
INSERT INTO Countries (CountryCode, FullName) VALUES ('NIG', 'Niger');
INSERT INTO Countries (CountryCode, FullName) VALUES ('NOR', 'Norway');
INSERT INTO Countries (CountryCode, FullName) VALUES ('NRU', 'Nauru');
INSERT INTO Countries (CountryCode, FullName) VALUES ('NZL', 'New Zealand');
INSERT INTO Countries (CountryCode, FullName) VALUES ('OMA', 'Oman');
INSERT INTO Countries (CountryCode, FullName) VALUES ('PAK', 'Pakistan');
INSERT INTO Countries (CountryCode, FullName) VALUES ('PAN', 'Panama');
INSERT INTO Countries (CountryCode, FullName) VALUES ('PAR', 'Paraguay');
INSERT INTO Countries (CountryCode, FullName) VALUES ('PER', 'Peru');
INSERT INTO Countries (CountryCode, FullName) VALUES ('PHI', 'Philippines');
INSERT INTO Countries (CountryCode, FullName) VALUES ('PLE', 'Palestine');
INSERT INTO Countries (CountryCode, FullName) VALUES ('PLW', 'Palau');
INSERT INTO Countries (CountryCode, FullName) VALUES ('PNG', 'Papua New Guinea');
INSERT INTO Countries (CountryCode, FullName) VALUES ('POL', 'Poland');
INSERT INTO Countries (CountryCode, FullName) VALUES ('PRK', 'North Korea');
INSERT INTO Countries (CountryCode, FullName) VALUES ('PUR', 'Puerto Rico');
INSERT INTO Countries (CountryCode, FullName) VALUES ('QAT', 'Qatar');
INSERT INTO Countries (CountryCode, FullName) VALUES ('ROU', 'Romania');
INSERT INTO Countries (CountryCode, FullName) VALUES ('RSA', 'South Africa');
-- INSERT INTO Countries (CountryCode, FullName) VALUES ('RUS', 'Russia');
INSERT INTO Countries (CountryCode, FullName) VALUES ('RWA', 'Rwanda');
INSERT INTO Countries (CountryCode, FullName) VALUES ('SAM', 'Samoa');
INSERT INTO Countries (CountryCode, FullName) VALUES ('SEN', 'Senegal');
INSERT INTO Countries (CountryCode, FullName) VALUES ('SEY', 'Seychelles');
INSERT INTO Countries (CountryCode, FullName) VALUES ('SGP', 'Singapore');
INSERT INTO Countries (CountryCode, FullName) VALUES ('SKN', 'Saint Kitts and Nevis');
INSERT INTO Countries (CountryCode, FullName) VALUES ('SLE', 'Sierra Leone');
INSERT INTO Countries (CountryCode, FullName) VALUES ('SLO', 'Slovenia');
INSERT INTO Countries (CountryCode, FullName) VALUES ('SMR', 'San Marino');
INSERT INTO Countries (CountryCode, FullName) VALUES ('SOL', 'Solomon Islands');
INSERT INTO Countries (CountryCode, FullName) VALUES ('SOM', 'Somalia');
INSERT INTO Countries (CountryCode, FullName) VALUES ('SRB', 'Serbia');
INSERT INTO Countries (CountryCode, FullName) VALUES ('SRI', 'Sri Lanka');
INSERT INTO Countries (CountryCode, FullName) VALUES ('SSD', 'South Sudan');
INSERT INTO Countries (CountryCode, FullName) VALUES ('STP', 'São Tomé and Príncipe');
INSERT INTO Countries (CountryCode, FullName) VALUES ('SUD', 'Sudan');
INSERT INTO Countries (CountryCode, FullName) VALUES ('SUR', 'Suriname');
INSERT INTO Countries (CountryCode, FullName) VALUES ('SVK', 'Slovakia');
INSERT INTO Countries (CountryCode, FullName) VALUES ('SWZ', 'Swaziland');
INSERT INTO Countries (CountryCode, FullName) VALUES ('SYR', 'Syria');
INSERT INTO Countries (CountryCode, FullName) VALUES ('TAN', 'Tanzania');
INSERT INTO Countries (CountryCode, FullName) VALUES ('TGA', 'Tonga');
INSERT INTO Countries (CountryCode, FullName) VALUES ('THA', 'Thailand');
INSERT INTO Countries (CountryCode, FullName) VALUES ('TJK', 'Tajikistan');
INSERT INTO Countries (CountryCode, FullName) VALUES ('TKM', 'Turkmenistan');
INSERT INTO Countries (CountryCode, FullName) VALUES ('TLS', 'East Timor');
INSERT INTO Countries (CountryCode, FullName) VALUES ('TOG', 'Togo');
INSERT INTO Countries (CountryCode, FullName) VALUES ('TPE', 'Chinese Taipei');
INSERT INTO Countries (CountryCode, FullName) VALUES ('TTO', 'Trinidad and Tobago');
INSERT INTO Countries (CountryCode, FullName) VALUES ('TUN', 'Tunisia');
INSERT INTO Countries (CountryCode, FullName) VALUES ('TUR', 'Turkey');
INSERT INTO Countries (CountryCode, FullName) VALUES ('TUV', 'Tuvalu');
INSERT INTO Countries (CountryCode, FullName) VALUES ('UAE', 'United Arab Emirates');
INSERT INTO Countries (CountryCode, FullName) VALUES ('UGA', 'Uganda');
INSERT INTO Countries (CountryCode, FullName) VALUES ('UKR', 'Ukraine');
INSERT INTO Countries (CountryCode, FullName) VALUES ('URU', 'Uruguay');
INSERT INTO Countries (CountryCode, FullName) VALUES ('USA', 'United States');
INSERT INTO Countries (CountryCode, FullName) VALUES ('UZB', 'Uzbekistan');
INSERT INTO Countries (CountryCode, FullName) VALUES ('VAN', 'Vanuatu');
INSERT INTO Countries (CountryCode, FullName) VALUES ('VEN', 'Venezuela');
INSERT INTO Countries (CountryCode, FullName) VALUES ('VIE', 'Vietnam');
INSERT INTO Countries (CountryCode, FullName) VALUES ('VIN', 'Saint Vincent and the Grenadines');
INSERT INTO Countries (CountryCode, FullName) VALUES ('YEM', 'Yemen');
INSERT INTO Countries (CountryCode, FullName) VALUES ('ZAM', 'Zambia');
INSERT INTO Countries (CountryCode, FullName) VALUES ('ZIM', 'Zimbabwe');
